In [1]:
# Importing the required libraries
import pandas as pd
import geopandas as gpd

# Reading the GeoJSON file
file_path = './YS_POIs.geojson'
gdf = gpd.read_file(file_path)

gdf

,OBJECTID_1,Name,Other,geometry
0,1,Grebe Lake Trailhead Parking,Parking Lot,POINT (-110.54970 44.71765)
1,2,Gneiss Creek Trailhead,Trailhead,POINT (-111.09714 44.79316)
2,3,Grassy Lake Trailhead,Trailhead,POINT (-110.82364 44.13264)
3,4,Grebe Lake Trailhead,Trailhead,POINT (-110.54968 44.71794)
4,5,Grizzly Lake Trailhead,Trailhead,POINT (-110.74539 44.79916)
...,...,...,...,...
1380,1381,Apollinaris Spring Comfort Station,Flush Toilet,POINT (-110.73417 44.84283)
1381,1382,Apollinaris Picnic Area Vault Toilet,Vault Toilet,POINT (-110.73395 44.84255)
1382,1383,Apollinaris Picnic Area Vault Toilet,Vault Toilet,POINT (-110.73390 44.84253)
1383,1384,Norris Campground Entrance Comfort Station,Flush Toilet,POINT (-110.69438 44.73731)
1384,1385,Snake River Picnic Area Vault Toilet,Vault Toilet,POINT (-110.66659 44.13703)

In [2]:
# Filtering the GeoDataFrame
filtered_gdf = gdf[gdf['Name'].notnull() & gdf['Name'].str.match(r'^[A-Za-z\s]+$', na=False)]
filtered_gdf = filtered_gdf.reset_index(drop=True)

filtered_gdf

,OBJECTID_1,Name,Other,geometry
0,1,Grebe Lake Trailhead Parking,Parking Lot,POINT (-110.54970 44.71765)
1,2,Gneiss Creek Trailhead,Trailhead,POINT (-111.09714 44.79316)
2,3,Grassy Lake Trailhead,Trailhead,POINT (-110.82364 44.13264)
3,4,Grebe Lake Trailhead,Trailhead,POINT (-110.54968 44.71794)
4,5,Grizzly Lake Trailhead,Trailhead,POINT (-110.74539 44.79916)
...,...,...,...,...
975,1381,Apollinaris Spring Comfort Station,Flush Toilet,POINT (-110.73417 44.84283)
976,1382,Apollinaris Picnic Area Vault Toilet,Vault Toilet,POINT (-110.73395 44.84255)
977,1383,Apollinaris Picnic Area Vault Toilet,Vault Toilet,POINT (-110.73390 44.84253)
978,1384,Norris Campground Entrance Comfort Station,Flush Toilet,POINT (-110.69438 44.73731)
979,1385,Snake River Picnic Area Vault Toilet,Vault Toilet,POINT (-110.66659 44.13703)

In [3]:
# Adding new columns to the GeoDataFrame
filtered_gdf["Time"] = 0
filtered_gdf.rename(columns={'Other': 'Type'}, inplace=True)

filtered_gdf

,OBJECTID_1,Name,Type,geometry,Time
0,1,Grebe Lake Trailhead Parking,Parking Lot,POINT (-110.54970 44.71765),0
1,2,Gneiss Creek Trailhead,Trailhead,POINT (-111.09714 44.79316),0
2,3,Grassy Lake Trailhead,Trailhead,POINT (-110.82364 44.13264),0
3,4,Grebe Lake Trailhead,Trailhead,POINT (-110.54968 44.71794),0
4,5,Grizzly Lake Trailhead,Trailhead,POINT (-110.74539 44.79916),0
...,...,...,...,...,...
975,1381,Apollinaris Spring Comfort Station,Flush Toilet,POINT (-110.73417 44.84283),0
976,1382,Apollinaris Picnic Area Vault Toilet,Vault Toilet,POINT (-110.73395 44.84255),0
977,1383,Apollinaris Picnic Area Vault Toilet,Vault Toilet,POINT (-110.73390 44.84253),0
978,1384,Norris Campground Entrance Comfort Station,Flush Toilet,POINT (-110.69438 44.73731),0
979,1385,Snake River Picnic Area Vault Toilet,Vault Toilet,POINT (-110.66659 44.13703),0

In [4]:
# Removing the 'OBJECTID_1' column
filtered_gdf.drop(columns=['OBJECTID_1'], inplace=True)

filtered_gdf

,Name,Type,geometry,Time
0,Grebe Lake Trailhead Parking,Parking Lot,POINT (-110.54970 44.71765),0
1,Gneiss Creek Trailhead,Trailhead,POINT (-111.09714 44.79316),0
2,Grassy Lake Trailhead,Trailhead,POINT (-110.82364 44.13264),0
3,Grebe Lake Trailhead,Trailhead,POINT (-110.54968 44.71794),0
4,Grizzly Lake Trailhead,Trailhead,POINT (-110.74539 44.79916),0
...,...,...,...,...
975,Apollinaris Spring Comfort Station,Flush Toilet,POINT (-110.73417 44.84283),0
976,Apollinaris Picnic Area Vault Toilet,Vault Toilet,POINT (-110.73395 44.84255),0
977,Apollinaris Picnic Area Vault Toilet,Vault Toilet,POINT (-110.73390 44.84253),0
978,Norris Campground Entrance Comfort Station,Flush Toilet,POINT (-110.69438 44.73731),0
979,Snake River Picnic Area Vault Toilet,Vault Toilet,POINT (-110.66659 44.13703),0

In [5]:
# Dropping the duplicate rows
filtered_gdf = filtered_gdf.drop_duplicates(subset=['Name', 'Type'])

filtered_gdf = filtered_gdf.reset_index(drop=True)

filtered_gdf

,Name,Type,geometry,Time
0,Grebe Lake Trailhead Parking,Parking Lot,POINT (-110.54970 44.71765),0
1,Gneiss Creek Trailhead,Trailhead,POINT (-111.09714 44.79316),0
2,Grassy Lake Trailhead,Trailhead,POINT (-110.82364 44.13264),0
3,Grebe Lake Trailhead,Trailhead,POINT (-110.54968 44.71794),0
4,Grizzly Lake Trailhead,Trailhead,POINT (-110.74539 44.79916),0
...,...,...,...,...
846,Brink of the Lower Falls Comfort Station,Flush Toilet,POINT (-110.49769 44.71998),0
847,Indian Creek Warming Hut Vault Toilet,Vault Toilet,POINT (-110.73501 44.88269),0
848,Apollinaris Spring Comfort Station,Flush Toilet,POINT (-110.73417 44.84283),0
849,Norris Campground Entrance Comfort Station,Flush Toilet,POINT (-110.69438 44.73731),0
850,Snake River Picnic Area Vault Toilet,Vault Toilet,POINT (-110.66659 44.13703),0

In [6]:
# Renaming the columns
filtered_gdf.rename(columns={'Type': 'Subcategory'}, inplace=True)
filtered_gdf["Type"] = "POI"

filtered_gdf

,Name,Subcategory,geometry,Time,Type
0,Grebe Lake Trailhead Parking,Parking Lot,POINT (-110.54970 44.71765),0,POI
1,Gneiss Creek Trailhead,Trailhead,POINT (-111.09714 44.79316),0,POI
2,Grassy Lake Trailhead,Trailhead,POINT (-110.82364 44.13264),0,POI
3,Grebe Lake Trailhead,Trailhead,POINT (-110.54968 44.71794),0,POI
4,Grizzly Lake Trailhead,Trailhead,POINT (-110.74539 44.79916),0,POI
...,...,...,...,...,...
846,Brink of the Lower Falls Comfort Station,Flush Toilet,POINT (-110.49769 44.71998),0,POI
847,Indian Creek Warming Hut Vault Toilet,Vault Toilet,POINT (-110.73501 44.88269),0,POI
848,Apollinaris Spring Comfort Station,Flush Toilet,POINT (-110.73417 44.84283),0,POI
849,Norris Campground Entrance Comfort Station,Flush Toilet,POINT (-110.69438 44.73731),0,POI
850,Snake River Picnic Area Vault Toilet,Vault Toilet,POINT (-110.66659 44.13703),0,POI

In [7]:
# Replacing the values in the 'Subcategory' column
filtered_gdf['Subcategory'] = filtered_gdf['Subcategory'].replace({
    'Mountain Pass (Saddle / Gap)': 'Mountain Pass',
    'Point of Interest': 'Viewpoint'
})

filtered_gdf = filtered_gdf[filtered_gdf['Subcategory'] != 'Locale']

filtered_gdf

,Name,Subcategory,geometry,Time,Type
0,Grebe Lake Trailhead Parking,Parking Lot,POINT (-110.54970 44.71765),0,POI
1,Gneiss Creek Trailhead,Trailhead,POINT (-111.09714 44.79316),0,POI
2,Grassy Lake Trailhead,Trailhead,POINT (-110.82364 44.13264),0,POI
3,Grebe Lake Trailhead,Trailhead,POINT (-110.54968 44.71794),0,POI
4,Grizzly Lake Trailhead,Trailhead,POINT (-110.74539 44.79916),0,POI
...,...,...,...,...,...
846,Brink of the Lower Falls Comfort Station,Flush Toilet,POINT (-110.49769 44.71998),0,POI
847,Indian Creek Warming Hut Vault Toilet,Vault Toilet,POINT (-110.73501 44.88269),0,POI
848,Apollinaris Spring Comfort Station,Flush Toilet,POINT (-110.73417 44.84283),0,POI
849,Norris Campground Entrance Comfort Station,Flush Toilet,POINT (-110.69438 44.73731),0,POI
850,Snake River Picnic Area Vault Toilet,Vault Toilet,POINT (-110.66659 44.13703),0,POI

In [8]:
# Categorizing the subcategories of the POIs
mountain_features = ['Valley', 'Basin', 'Peak', 'Mountain Pass']
filtered_gdf.loc[filtered_gdf['Subcategory'].isin(mountain_features), 'Type'] = 'Mountain'

water_features = ['Geyser', 'Waterfall', 'Lake']
filtered_gdf.loc[filtered_gdf['Subcategory'].isin(water_features), 'Type'] = 'Water'

transportation_features = ['Parking Lot', 'Roadside Pullout', 'Boat Launch', 'Entrance Station']
filtered_gdf.loc[filtered_gdf['Subcategory'].isin(transportation_features), 'Type'] = 'Transportation'

visitor_services = ['Visitor Center', 'Ranger Station', 'Information', 'Post Office', 'Museum', 'Interpretive Exhibit']
filtered_gdf.loc[filtered_gdf['Subcategory'].isin(visitor_services), 'Type'] = 'Service'

restroom_features = ['Vault Toilet', 'Flush Toilet', 'Dump Station']
filtered_gdf.loc[filtered_gdf['Subcategory'].isin(restroom_features), 'Type'] = 'Restroom'

commerce_features = ['Store', 'Food Service', 'Lodging']
filtered_gdf.loc[filtered_gdf['Subcategory'].isin(commerce_features), 'Type'] = 'Commerce'

outdoor_activities = ['Campground', 'RV Campground', 'Picnic Area', 'Amphitheater', 'Horseback Riding', 'Bench']
filtered_gdf.loc[filtered_gdf['Subcategory'].isin(outdoor_activities), 'Type'] = 'Recreation'

tourist_attractions = ['Trailhead', 'Viewpoint']
filtered_gdf.loc[filtered_gdf['Subcategory'].isin(tourist_attractions), 'Type'] = 'Tourism'

filtered_gdf

,Name,Subcategory,geometry,Time,Type
0,Grebe Lake Trailhead Parking,Parking Lot,POINT (-110.54970 44.71765),0,Transportation
1,Gneiss Creek Trailhead,Trailhead,POINT (-111.09714 44.79316),0,Tourism
2,Grassy Lake Trailhead,Trailhead,POINT (-110.82364 44.13264),0,Tourism
3,Grebe Lake Trailhead,Trailhead,POINT (-110.54968 44.71794),0,Tourism
4,Grizzly Lake Trailhead,Trailhead,POINT (-110.74539 44.79916),0,Tourism
...,...,...,...,...,...
846,Brink of the Lower Falls Comfort Station,Flush Toilet,POINT (-110.49769 44.71998),0,Restroom
847,Indian Creek Warming Hut Vault Toilet,Vault Toilet,POINT (-110.73501 44.88269),0,Restroom
848,Apollinaris Spring Comfort Station,Flush Toilet,POINT (-110.73417 44.84283),0,Restroom
849,Norris Campground Entrance Comfort Station,Flush Toilet,POINT (-110.69438 44.73731),0,Restroom
850,Snake River Picnic Area Vault Toilet,Vault Toilet,POINT (-110.66659 44.13703),0,Restroom

In [9]:
# Grouping the GeoDataFrame by the 'Subcategory' column
type_counts = filtered_gdf.groupby('Subcategory').size().reset_index(name='Count')

type_counts = type_counts.sort_values(by='Count', ascending=False)

type_counts = type_counts.reset_index(drop=True)

type_counts

             Subcategory  Count
0                 Geyser    170
1            Parking Lot    120
2              Trailhead    118
3           Vault Toilet    104
4                   Peak     49
5            Picnic Area     47
6                  Store     32
7           Flush Toilet     30
8              Viewpoint     22
9              Waterfall     20
10          Food Service     20
11        Ranger Station     14
12                 Basin     13
13            Campground     11
14        Visitor Center      7
15          Amphitheater      7
16               Lodging      7
17      Entrance Station      7
18           Post Office      5
19                Valley      5
20          Dump Station      5
21           Information      4
22                Museum      3
23           Boat Launch      3
24         Mountain Pass      3
25      Horseback Riding      2
26                  Lake      1
27  Interpretive Exhibit      1
28         RV Campground      1
29      Roadside Pullout      1
30                 Bench      1

In [10]:
# Grouping the GeoDataFrame by the 'Type' column
type_counts = filtered_gdf.groupby('Type').size().reset_index(name='Count')

type_counts = type_counts.sort_values(by='Count', ascending=False)

type_counts = type_counts.reset_index(drop=True)

type_counts

             Type  Count
0           Water    191
1         Tourism    140
2        Restroom    139
3  Transportation    131
4        Mountain     70
5      Recreation     69
6        Commerce     59
7         Service     34

In [11]:
# Copying the GeoDataFrame
time_gdf = filtered_gdf.copy()

time_gdf

,Name,Subcategory,geometry,Time,Type
0,Grebe Lake Trailhead Parking,Parking Lot,POINT (-110.54970 44.71765),0,Transportation
1,Gneiss Creek Trailhead,Trailhead,POINT (-111.09714 44.79316),0,Tourism
2,Grassy Lake Trailhead,Trailhead,POINT (-110.82364 44.13264),0,Tourism
3,Grebe Lake Trailhead,Trailhead,POINT (-110.54968 44.71794),0,Tourism
4,Grizzly Lake Trailhead,Trailhead,POINT (-110.74539 44.79916),0,Tourism
...,...,...,...,...,...
846,Brink of the Lower Falls Comfort Station,Flush Toilet,POINT (-110.49769 44.71998),0,Restroom
847,Indian Creek Warming Hut Vault Toilet,Vault Toilet,POINT (-110.73501 44.88269),0,Restroom
848,Apollinaris Spring Comfort Station,Flush Toilet,POINT (-110.73417 44.84283),0,Restroom
849,Norris Campground Entrance Comfort Station,Flush Toilet,POINT (-110.69438 44.73731),0,Restroom
850,Snake River Picnic Area Vault Toilet,Vault Toilet,POINT (-110.66659 44.13703),0,Restroom

In [12]:
# Importing the required library
import numpy as np

np.random.seed(0)

# Generating random values for the 'Time' column for the 'Mountain' type
mountain_times = np.arange(60, 125, 5)
time_gdf.loc[time_gdf['Type'] == 'Mountain', 'Time'] = (
    ['~ ' + str(t) for t in np.random.choice(mountain_times, size=time_gdf[time_gdf['Type'] == 'Mountain'].shape[0])]
)

time_gdf[time_gdf['Type'] == 'Mountain']

,Name,Subcategory,geometry,Time,Type
416,Pelican Valley,Valley,POINT (-110.35298 44.56383),~ 120,Mountain
417,Pleasant Valley,Valley,POINT (-110.42131 44.92938),~ 85,Mountain
424,Secret Valley,Valley,POINT (-110.76938 44.65855),~ 60,Mountain
452,Craig Pass,Mountain Pass,POINT (-110.71947 44.44128),~ 75,Mountain
459,Dunraven Pass,Mountain Pass,POINT (-110.45443 44.78497),~ 115,Mountain
...,...,...,...,...,...
677,Black Butte,Peak,POINT (-111.09689 45.03187),~ 80,Mountain
678,King Butte,Peak,POINT (-111.08022 45.06799),~ 105,Mountain
679,Lava Butte,Peak,POINT (-111.10550 45.05326),~ 110,Mountain
680,Meldrum Mountain,Peak,POINT (-111.01578 45.04743),~ 110,Mountain
681,Shooting Star Mountain,Peak,POINT (-110.95689 45.07604),~ 100,Mountain

In [13]:
# Generating random values for the 'Time' column for the 'Water' type
water_times = np.arange(40, 95, 5)
time_gdf.loc[time_gdf['Type'] == 'Water', 'Time'] = (
    ['~ ' + str(t) for t in np.random.choice(water_times, size=time_gdf[time_gdf['Type'] == 'Water'].shape[0])]
)

time_gdf[time_gdf['Type'] == 'Water']

,Name,Subcategory,geometry,Time,Type
97,Emerald Pool,Geyser,POINT (-110.85520 44.46101),~ 45,Water
100,Biscuit Basin Geyser,Geyser,POINT (-110.85049 44.48160),~ 45,Water
102,Artemisia Geyser,Geyser,POINT (-110.84855 44.47830),~ 75,Water
103,Anemone Geyser,Geyser,POINT (-110.82898 44.46274),~ 85,Water
105,Mirror Pool,Geyser,POINT (-110.85027 44.48313),~ 85,Water
...,...,...,...,...,...
671,Whales Mouth,Geyser,POINT (-110.70530 44.72859),~ 45,Water
672,Whirligig Geyser,Geyser,POINT (-110.70314 44.72869),~ 45,Water
673,White Dome Geyser,Geyser,POINT (-110.80282 44.53935),~ 40,Water
674,Yellow Funnel Spring,Geyser,POINT (-110.70703 44.72101),~ 55,Water
675,Young Hopeful Geyser,Geyser,POINT (-110.78443 44.54400),~ 80,Water

In [14]:
# Generating random values for the 'Time' column for the 'Tourism' type
tourism_times = np.arange(20, 84, 4)
time_gdf.loc[time_gdf['Type'] == 'Tourism', 'Time'] = (
    ['~ ' + str(t) for t in np.random.choice(tourism_times, size=time_gdf[time_gdf['Type'] == 'Tourism'].shape[0])]
)

time_gdf[time_gdf['Type'] == 'Tourism']

,Name,Subcategory,geometry,Time,Type
1,Gneiss Creek Trailhead,Trailhead,POINT (-111.09714 44.79316),~ 64,Tourism
2,Grassy Lake Trailhead,Trailhead,POINT (-110.82364 44.13264),~ 52,Tourism
3,Grebe Lake Trailhead,Trailhead,POINT (-110.54968 44.71794),~ 36,Tourism
4,Grizzly Lake Trailhead,Trailhead,POINT (-110.74539 44.79916),~ 36,Tourism
5,Harlequin Lake Trailhead,Trailhead,POINT (-110.88744 44.64032),~ 20,Tourism
...,...,...,...,...,...
761,Fossil Forest Trailhead,Trailhead,POINT (-110.32789 44.91193),~ 40,Tourism
764,Fountain Paint Pots Trailhead,Trailhead,POINT (-110.80834 44.54756),~ 60,Tourism
766,Glacial Boulder Trailhead,Trailhead,POINT (-110.47263 44.72959),~ 64,Tourism
768,Glen Creek Trailhead,Trailhead,POINT (-110.72762 44.93294),~ 48,Tourism
835,Mary Mountain West Trailhead,Trailhead,POINT (-110.81612 44.56993),~ 68,Tourism

In [15]:
# Generating random values for the 'Time' column for the 'Restroom' type
restroom_times = np.arange(4, 12, 2)
time_gdf.loc[time_gdf['Type'] == 'Restroom', 'Time'] = (
    ['~ ' + str(t) for t in np.random.choice(restroom_times, size=time_gdf[time_gdf['Type'] == 'Restroom'].shape[0])]
)

time_gdf[time_gdf['Type'] == 'Restroom']

,Name,Subcategory,geometry,Time,Type
96,Bridge Bay RV Dump Station,Dump Station,POINT (-110.43715 44.53333),~ 4,Restroom
109,Canyon CG RV Dump Station,Dump Station,POINT (-110.48849 44.73612),~ 8,Restroom
275,Fishing Bridge RV Dump Station,Dump Station,POINT (-110.37016 44.56363),~ 6,Restroom
285,Grant Village CG RV Dump Site,Dump Station,POINT (-110.56464 44.39493),~ 10,Restroom
317,Madison CG RV Dump Site,Dump Station,POINT (-110.86077 44.64533),~ 6,Restroom
...,...,...,...,...,...
846,Brink of the Lower Falls Comfort Station,Flush Toilet,POINT (-110.49769 44.71998),~ 6,Restroom
847,Indian Creek Warming Hut Vault Toilet,Vault Toilet,POINT (-110.73501 44.88269),~ 4,Restroom
848,Apollinaris Spring Comfort Station,Flush Toilet,POINT (-110.73417 44.84283),~ 4,Restroom
849,Norris Campground Entrance Comfort Station,Flush Toilet,POINT (-110.69438 44.73731),~ 6,Restroom
850,Snake River Picnic Area Vault Toilet,Vault Toilet,POINT (-110.66659 44.13703),~ 4,Restroom

In [16]:
# Generating random values for the 'Time' column for the 'Transportation' type
transportation_times = np.arange(10, 24, 4)
time_gdf.loc[time_gdf['Type'] == 'Transportation', 'Time'] = (
    ['~ ' + str(t) for t in np.random.choice(transportation_times, size=time_gdf[time_gdf['Type'] == 'Transportation'].shape[0])]
)

time_gdf[time_gdf['Type'] == 'Transportation']

,Name,Subcategory,geometry,Time,Type
0,Grebe Lake Trailhead Parking,Parking Lot,POINT (-110.54970 44.71765),~ 10,Transportation
14,Heart Lake Trail Parking Loop,Parking Lot,POINT (-110.59842 44.31712),~ 18,Transportation
18,History Exhibit Parking,Parking Lot,POINT (-110.96258 44.66195),~ 10,Transportation
20,Lewis Lake Gravel Pit,Parking Lot,POINT (-110.60254 44.31428),~ 10,Transportation
22,Lone Star Geyser Trailhead Parking,Parking Lot,POINT (-110.80431 44.44456),~ 14,Transportation
...,...,...,...,...,...
650,Daly Creek Trailhead Parking,Parking Lot,POINT (-111.13978 45.04839),~ 14,Transportation
652,Grant Restaurant and Post Office Service Parking,Parking Lot,POINT (-110.55536 44.39095),~ 14,Transportation
653,Grant Service Station Parking,Parking Lot,POINT (-110.55831 44.38939),~ 18,Transportation
656,Grant Store Parking,Parking Lot,POINT (-110.55645 44.38925),~ 18,Transportation
658,Grant Visitor Center Parking,Parking Lot,POINT (-110.55666 44.39317),~ 10,Transportation

In [17]:
# Generating random values for the 'Time' column for the 'Recreation' type
recreation_times = np.arange(60, 130, 10)
time_gdf.loc[time_gdf['Type'] == 'Recreation', 'Time'] = (
    ['~ ' + str(t) for t in np.random.choice(recreation_times, size=time_gdf[time_gdf['Type'] == 'Recreation'].shape[0])]
)

time_gdf[time_gdf['Type'] == 'Recreation']

,Name,Subcategory,geometry,Time,Type
40,Apollinaris Picnic Area,Picnic Area,POINT (-110.73458 44.84247),~ 120,Recreation
56,Beaver Lake Picnic Area,Picnic Area,POINT (-110.73223 44.81144),~ 110,Recreation
88,Bridge Bay Campground,Campground,POINT (-110.43692 44.53444),~ 90,Recreation
94,Bridge Bay Picnic Area,Picnic Area,POINT (-110.43656 44.53296),~ 120,Recreation
101,Caldera Rim Picnic Area,Picnic Area,POINT (-110.74971 44.65980),~ 100,Recreation
...,...,...,...,...,...
396,Tower Fall Campground Amphitheater,Amphitheater,POINT (-110.38922 44.88905),~ 120,Recreation
462,Lewis Lake Picnic Area,Picnic Area,POINT (-110.62788 44.28308),~ 70,Recreation
582,,Bench,POINT (-110.84157 44.47324),~ 110,Recreation
621,Yellowstone River Picnic Area,Picnic Area,POINT (-110.40034 44.91697),~ 110,Recreation
668,Albright Picnic Area,Picnic Area,POINT (-110.70011 44.97616),~ 110,Recreation

In [18]:
# Generating random values for the 'Time' column for the 'Commerce' type
commerce_times = np.arange(30, 70, 5)
time_gdf.loc[time_gdf['Type'] == 'Commerce', 'Time'] = (
    ['~ ' + str(t) for t in np.random.choice(commerce_times, size=time_gdf[time_gdf['Type'] == 'Commerce'].shape[0])]
)

time_gdf[time_gdf['Type'] == 'Commerce']

,Name,Subcategory,geometry,Time,Type
25,Albright Visitor Center Bookstore,Store,POINT (-110.69961 44.97646),~ 60,Commerce
91,Bridge Bay Marina Store,Store,POINT (-110.43911 44.53317),~ 30,Commerce
104,Canyon Adventure Store,Store,POINT (-110.49195 44.73413),~ 35,Commerce
106,Canyon Cafeteria,Food Service,POINT (-110.48994 44.73340),~ 60,Commerce
121,Canyon General Store Grill,Food Service,POINT (-110.49113 44.73365),~ 65,Commerce
125,Canyon General Store Grocery,Store,POINT (-110.49161 44.73375),~ 55,Commerce
135,Canyon General Store,Store,POINT (-110.49138 44.73369),~ 65,Commerce
139,Canyon Gift Shop,Store,POINT (-110.48968 44.73407),~ 35,Commerce
143,Canyon Lodge and Cabins,Lodging,POINT (-110.48959 44.73430),~ 55,Commerce
150,Canyon Service Station,Store,POINT (-110.49236 44.73654),~ 60,Commerce
162,Canyon Visitor Center Bookstore,Store,POINT (-110.49196 44.73480),~ 50,Commerce
194,Lake General Store,Store,POINT (-110.39644 44.55001),~ 40,Commerce
197,Lake General Store,Food Service,POINT (-110.39639 44.55022),~ 40,Commerce
214,Fishing Bridge Service Station,Store,POINT (-110.37606 44.56497),~ 45,Commerce
233,Roosevelt Store,Store,POINT (-110.41718 44.91283),~ 60,Commerce
252,Fishing Bridge General Store Grill,Food Service,POINT (-110.37537 44.56495),~ 60,Commerce
256,Fishing Bridge General Store,Store,POINT (-110.37526 44.56477),~ 60,Commerce
278,Fishing Bridge Visitor Center Bookstore,Store,POINT (-110.37784 44.56304),~ 30,Commerce
287,Grant Village Dining Room,Food Service,POINT (-110.55470 44.39235),~ 65,Commerce
288,Grant Village General Store,Store,POINT (-110.55594 44.38898),~ 55,Commerce
289,Grant Village Grill,Food Service,POINT (-110.55592 44.38917),~ 55,Commerce
290,Grant Village Lake House Restaurant,Food Service,POINT (-110.55235 44.39250),~ 65,Commerce
291,Grant Village Lodging,Lodging,POINT (-110.55542 44.38954),~ 45,Commerce
292,Grant Village Mini Store,Store,POINT (-110.55793 44.38934),~ 40,Commerce
297,Grant Village Service Station,Store,POINT (-110.55863 44.38915),~ 45,Commerce
298,Grant Village VC Bookstore,Store,POINT (-110.55645 44.39365),~ 40,Commerce
304,Lake Hotel Deli,Food Service,POINT (-110.40013 44.54984),~ 40,Commerce
305,Lake Hotel Dining Room,Food Service,POINT (-110.40112 44.54987),~ 35,Commerce
306,Lake Hotel Gift Shop,Store,POINT (-110.40069 44.54985),~ 45,Commerce
307,Lake Hotel and Cabins,Lodging,POINT (-110.40048 44.54985),~ 35,Commerce
308,Lake Lodge Cabins,Lodging,POINT (-110.39579 44.55505),~ 45,Commerce
309,Lake Lodge Cafeteria,Food Service,POINT (-110.39572 44.55517),~ 55,Commerce
310,Lake Lodge Gift Shop,Store,POINT (-110.39586 44.55491),~ 60,Commerce
316,Madison Bookstore,Store,POINT (-110.86211 44.64222),~ 40,Commerce
324,Mammoth General Store,Store,POINT (-110.70339 44.97560),~ 55,Commerce
325,Mammoth Dining Room,Food Service,POINT (-110.70239 44.97597),~ 40,Commerce
329,Mammoth Service Station,Store,POINT (-110.70372 44.97529),~ 50,Commerce
333,Norris Geyser Basin Bookstore,Store,POINT (-110.70317 44.72617),~ 35,Commerce
340,Old Faithful Basin Store Grill,Food Service,POINT (-110.83376 44.46083),~ 55,Commerce
341,Old Faithful Basin Store,Store,POINT (-110.83355 44.46079),~ 65,Commerce
342,Old Faithful General Store Grill,Food Service,POINT (-110.82769 44.45685),~ 60,Commerce
343,Old Faithful General Store Grocery,Store,POINT (-110.82803 44.45695),~ 30,Commerce
344,Old Faithful General Store,Store,POINT (-110.82785 44.45692),~ 45,Commerce
345,Old Faithful Inn Dining Room,Food Service,POINT (-110.83139 44.45978),~ 55,Commerce
346,Old Faithful Inn Gift Shop,Store,POINT (-110.83102 44.45986),~ 30,Commerce
347,Old Faithful Inn,Lodging,POINT (-110.83121 44.45996),~ 50,Commerce
348,Old Faithful Lodge Cafeteria,Food Service,POINT (-110.82604 44.45940),~ 40,Commerce
349,Old Faithful Lodge,Lodging,POINT (-110.82543 44.45910),~ 35,Commerce
352,Old Faithful Snow Lodge Geyser Grill,Food Service,POINT (-110.82885 44.45714),~ 65,Commerce
353,Old Faithful Snow Lodge Gift Shop,Store,POINT (-110.82961 44.45671),~ 30,Commerce
354,Old Faithful Snow Lodge Obsidian Dining Room,Food Service,POINT (-110.82986 44.45679),~ 35,Commerce
355,Old Faithful Snow Lodge,Lodging,POINT (-110.82944 44.45669),~ 40,Commerce
361,Roosevelt Lodge Dining Room,Food Service,POINT (-110.41699 44.91250),~ 35,Commerce
362,Roosevelt Old West Dinner Cookout,Food Service,POINT (-110.41314 44.91401),~ 60,Commerce
374,Terrace Grill,Food Service,POINT (-110.70267 44.97581),~ 35,Commerce
376,Tower Fall General Store,Store,POINT (-110.38692 44.89199),~ 65,Commerce
378,Tower Junction Service Station,Store,POINT (-110.41749 44.91604),~ 55,Commerce
384,West Thumb Bookstore,Store,POINT (-110.57334 44.41578),~ 45,Commerce
460,Old Faithful Visitor Education Center Bookstore,Store,POINT (-110.82946 44.45864),~ 60,Commerce

In [19]:
# Generating random values for the 'Time' column for the 'Service' type
service_times = np.arange(30, 60, 5)
time_gdf.loc[time_gdf['Type'] == 'Service', 'Time'] = (
    ['~ ' + str(t) for t in np.random.choice(service_times, size=time_gdf[time_gdf['Type'] == 'Service'].shape[0])]
)

time_gdf[time_gdf['Type'] == 'Service']

,Name,Subcategory,geometry,Time,Type
75,Bechler Ranger Station,Ranger Station,POINT (-111.04633 44.14975),~ 30,Service
98,Bridge Bay Ranger Station,Ranger Station,POINT (-110.43970 44.53335),~ 50,Service
145,Canyon Post Office,Post Office,POINT (-110.48956 44.73463),~ 35,Service
147,Canyon Ranger Station,Ranger Station,POINT (-110.49096 44.73628),~ 35,Service
184,Madison Information Station,Visitor Center,POINT (-110.86214 44.64225),~ 55,Service
198,Lake Ranger Station,Ranger Station,POINT (-110.39468 44.55107),~ 50,Service
235,East Entrance Ranger Station,Ranger Station,POINT (-110.00485 44.48906),~ 30,Service
274,Fishing Bridge Museum,Museum,POINT (-110.37765 44.56299),~ 40,Service
279,Fishing Bridge Visitor Center,Visitor Center,POINT (-110.37775 44.56302),~ 45,Service
282,Grant Backcountry Office,Information,POINT (-110.55815 44.38929),~ 50,Service
284,Grant Ranger Station,Ranger Station,POINT (-110.56450 44.38627),~ 35,Service
295,Grant Village Post Office,Post Office,POINT (-110.55487 44.39074),~ 40,Service
296,Grant Village Registration,Information,POINT (-110.55544 44.38963),~ 45,Service
299,Grant Village Visitor Center,Visitor Center,POINT (-110.55635 44.39359),~ 50,Service
311,Lake Post Office,Post Office,POINT (-110.40073 44.55108),~ 35,Service
320,Madison Junior Ranger Station,Ranger Station,POINT (-110.86211 44.64222),~ 30,Service
327,Mammoth Post Office,Post Office,POINT (-110.69892 44.97697),~ 50,Service
328,Mammoth Ranger Station,Ranger Station,POINT (-110.70053 44.97704),~ 35,Service
336,Norris Ranger Station,Ranger Station,POINT (-110.69461 44.73775),~ 40,Service
339,Northeast Entrance Ranger Station,Ranger Station,POINT (-110.01170 45.00457),~ 50,Service
350,Old Faithful Post Office,Post Office,POINT (-110.83145 44.45663),~ 45,Service
351,Old Faithful Ranger Station,Ranger Station,POINT (-110.83180 44.45688),~ 30,Service
356,Old Faithful Visitor Education Center,Visitor Center,POINT (-110.82923 44.45861),~ 50,Service
369,South Entrance Ranger Station,Ranger Station,POINT (-110.66638 44.13606),~ 55,Service
377,Tower Junction Ranger Station,Ranger Station,POINT (-110.41998 44.91633),~ 50,Service
383,West Entrance Ranger Station,Ranger Station,POINT (-111.08991 44.65660),~ 55,Service
385,West Thumb Information Station,Information,POINT (-110.57329 44.41579),~ 30,Service
388,West Thumb Information Center,Information,POINT (-110.57337 44.41579),~ 55,Service
389,Albright Visitor Center,Visitor Center,POINT (-110.69953 44.97637),~ 40,Service
450,Apollinaris Spring,Interpretive Exhibit,POINT (-110.73334 44.84266),~ 45,Service
464,Norris Geyser Basin Museum,Museum,POINT (-110.70355 44.72649),~ 35,Service
486,Norris Geyser Basin Museum,Visitor Center,POINT (-110.70363 44.72650),~ 40,Service
598,Museum of the National Park Ranger,Museum,POINT (-110.69696 44.73782),~ 35,Service
645,Canyon Visitor Education Center,Visitor Center,POINT (-110.49185 44.73472),~ 55,Service

In [20]:
# Grouping the GeoDataFrame by the 'Subcategory' column
type_counts = filtered_gdf.groupby('Subcategory').size().reset_index(name='Count')

type_counts = type_counts.sort_values(by='Count', ascending=False)

type_counts = type_counts.reset_index(drop=True)

type_counts

             Subcategory  Count
0                 Geyser    170
1            Parking Lot    120
2              Trailhead    118
3           Vault Toilet    104
4                   Peak     49
5            Picnic Area     47
6                  Store     32
7           Flush Toilet     30
8              Viewpoint     22
9              Waterfall     20
10          Food Service     20
11        Ranger Station     14
12                 Basin     13
13            Campground     11
14        Visitor Center      7
15          Amphitheater      7
16               Lodging      7
17      Entrance Station      7
18           Post Office      5
19                Valley      5
20          Dump Station      5
21           Information      4
22                Museum      3
23           Boat Launch      3
24         Mountain Pass      3
25      Horseback Riding      2
26                  Lake      1
27  Interpretive Exhibit      1
28         RV Campground      1
29      Roadside Pullout      1
30                 Bench      1

In [21]:
# Grouping the GeoDataFrame by the 'Type' column
type_counts = filtered_gdf.groupby('Type').size().reset_index(name='Count')

type_counts = type_counts.sort_values(by='Count', ascending=False)

type_counts = type_counts.reset_index(drop=True)

type_counts

             Type  Count
0           Water    191
1         Tourism    140
2        Restroom    139
3  Transportation    131
4        Mountain     70
5      Recreation     69
6        Commerce     59
7         Service     34

In [22]:
# Showing the GeoDataFrame
time_gdf

,Name,Subcategory,geometry,Time,Type
0,Grebe Lake Trailhead Parking,Parking Lot,POINT (-110.54970 44.71765),~ 10,Transportation
1,Gneiss Creek Trailhead,Trailhead,POINT (-111.09714 44.79316),~ 64,Tourism
2,Grassy Lake Trailhead,Trailhead,POINT (-110.82364 44.13264),~ 52,Tourism
3,Grebe Lake Trailhead,Trailhead,POINT (-110.54968 44.71794),~ 36,Tourism
4,Grizzly Lake Trailhead,Trailhead,POINT (-110.74539 44.79916),~ 36,Tourism
...,...,...,...,...,...
846,Brink of the Lower Falls Comfort Station,Flush Toilet,POINT (-110.49769 44.71998),~ 6,Restroom
847,Indian Creek Warming Hut Vault Toilet,Vault Toilet,POINT (-110.73501 44.88269),~ 4,Restroom
848,Apollinaris Spring Comfort Station,Flush Toilet,POINT (-110.73417 44.84283),~ 4,Restroom
849,Norris Campground Entrance Comfort Station,Flush Toilet,POINT (-110.69438 44.73731),~ 6,Restroom
850,Snake River Picnic Area Vault Toilet,Vault Toilet,POINT (-110.66659 44.13703),~ 4,Restroom

In [23]:
# Checking if there are rows with Time equal to 0
has_zero_time = (time_gdf['Time'] == 0).any()

if has_zero_time:
    print("There are rows with Time equal to 0.")

    print(time_gdf[time_gdf['Time'] == 0])
else:
    print("No rows with Time equal to 0.")

No rows with Time equal to 0.

In [24]:
# Checking the crs of the GeoDataFrame
time_gdf.crs

<Geographic 2D CRS: EPSG:4326>
Name: WGS 84
Axis Info [ellipsoidal]:
- Lat[north]: Geodetic latitude (degree)
- Lon[east]: Geodetic longitude (degree)
Area of Use:
- name: World.
- bounds: (-180.0, -90.0, 180.0, 90.0)
Datum: World Geodetic System 1984 ensemble
- Ellipsoid: WGS 84
- Prime Meridian: Greenwich

In [25]:
# Remove empty values from the 'Name' column
time_gdf = time_gdf.replace(' ', pd.NA)
time_gdf = time_gdf.dropna()

time_gdf

,Name,Subcategory,geometry,Time,Type
0,Grebe Lake Trailhead Parking,Parking Lot,POINT (-110.54970 44.71765),~ 10,Transportation
1,Gneiss Creek Trailhead,Trailhead,POINT (-111.09714 44.79316),~ 64,Tourism
2,Grassy Lake Trailhead,Trailhead,POINT (-110.82364 44.13264),~ 52,Tourism
3,Grebe Lake Trailhead,Trailhead,POINT (-110.54968 44.71794),~ 36,Tourism
4,Grizzly Lake Trailhead,Trailhead,POINT (-110.74539 44.79916),~ 36,Tourism
...,...,...,...,...,...
846,Brink of the Lower Falls Comfort Station,Flush Toilet,POINT (-110.49769 44.71998),~ 6,Restroom
847,Indian Creek Warming Hut Vault Toilet,Vault Toilet,POINT (-110.73501 44.88269),~ 4,Restroom
848,Apollinaris Spring Comfort Station,Flush Toilet,POINT (-110.73417 44.84283),~ 4,Restroom
849,Norris Campground Entrance Comfort Station,Flush Toilet,POINT (-110.69438 44.73731),~ 6,Restroom
850,Snake River Picnic Area Vault Toilet,Vault Toilet,POINT (-110.66659 44.13703),~ 4,Restroom

In [26]:
# Exporting the GeoDataFrame to a GeoJSON file
time_gdf.to_file('./YS_POIs_Cleaned.geojson', driver='GeoJSON')